/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Loop } from "./components/type-it/type-it";
export { Loop } from "./components/type-it/type-it";
export namespace Components {
    interface TypeIt {
        "loop": Loop;
        "sentences": string[];
        "start": () => Promise<string>;
        "stop": () => Promise<void>;
    }
}
declare global {
    interface HTMLTypeItElement extends Components.TypeIt, HTMLStencilElement {
    }
    var HTMLTypeItElement: {
        prototype: HTMLTypeItElement;
        new (): HTMLTypeItElement;
    };
    interface HTMLElementTagNameMap {
        "type-it": HTMLTypeItElement;
    }
}
declare namespace LocalJSX {
    interface TypeIt {
        "loop"?: Loop;
        "sentences"?: string[];
    }
    interface IntrinsicElements {
        "type-it": TypeIt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "type-it": LocalJSX.TypeIt & JSXBase.HTMLAttributes<HTMLTypeItElement>;
        }
    }
}
