/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Loop } from "./components/wc-typeit/wc-typeit";
export { Loop } from "./components/wc-typeit/wc-typeit";
export namespace Components {
    interface WcTypeit {
        "loop": Loop;
        "sentences": string[];
        "start": () => Promise<string>;
        "stop": () => Promise<string>;
    }
}
export interface WcTypeitCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcTypeitElement;
}
declare global {
    interface HTMLWcTypeitElementEventMap {
        "animationStop": void;
    }
    interface HTMLWcTypeitElement extends Components.WcTypeit, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcTypeitElementEventMap>(type: K, listener: (this: HTMLWcTypeitElement, ev: WcTypeitCustomEvent<HTMLWcTypeitElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcTypeitElementEventMap>(type: K, listener: (this: HTMLWcTypeitElement, ev: WcTypeitCustomEvent<HTMLWcTypeitElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcTypeitElement: {
        prototype: HTMLWcTypeitElement;
        new (): HTMLWcTypeitElement;
    };
    interface HTMLElementTagNameMap {
        "wc-typeit": HTMLWcTypeitElement;
    }
}
declare namespace LocalJSX {
    interface WcTypeit {
        "loop"?: Loop;
        "onAnimationStop"?: (event: WcTypeitCustomEvent<void>) => void;
        "sentences"?: string[];
    }
    interface IntrinsicElements {
        "wc-typeit": WcTypeit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-typeit": LocalJSX.WcTypeit & JSXBase.HTMLAttributes<HTMLWcTypeitElement>;
        }
    }
}
